name: deploy-aca (manual reducido)

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: "Resource Group"
        required: true
        default: "dockercurso"
      environment_name:
        description: "ACA Environment name"
        required: true
        default: "aca-env-compras"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # OIDC
      contents: read

    env:
      RG: ${{ inputs.resource_group }}
      ENV_NAME: ${{ inputs.environment_name }}
      LOC: eastus2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:  ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Echo summary
        run: |
          echo "=========== RESUMEN ==========="
          echo "RG:        $RG"
          echo "ENV:       $ENV_NAME ($LOC)"
          echo "================================"